### ISSUE TITLE
Replace Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [thoop/swg#9]
`new Buffer(...)` is deprecated and unsafe. Could it be replaced with `Buffer.from(...)` in [these places](https://github.com/thoop/swg/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22)?

**Comment by thoop** [comment]
It looks like in each case we immediately set the contents of the buffer so we don't look to be exposing anything...but yeah that should get changed. I only work on this repo once every few years for fun so maybe one day I'll get around to it :) Thanks!

**Comment by thoop** [comment]
@gabrielschulhof Since it was a pretty easy change, I went ahead and replaced the `new Buffer(...)` with `Buffer.from(...)` and `Buffer.alloc(...)`. Thanks for creating this issue.
